/*
 * Automatically generated by jrpcgen 1.0.5 on 18/06/04 18:47
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package com.infine.perfmeter.rstat;

import org.acplt.oncrpc.OncRpcException;
import org.acplt.oncrpc.XdrAble;
import org.acplt.oncrpc.XdrDecodingStream;
import org.acplt.oncrpc.XdrEncodingStream;

import java.io.IOException;

public class rstat_timeval implements XdrAble {
    public int tv_sec;
    public int tv_usec;

    public rstat_timeval() {
    }

    public rstat_timeval(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        xdr.xdrEncodeInt(tv_sec);
        xdr.xdrEncodeInt(tv_usec);
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        tv_sec = xdr.xdrDecodeInt();
        tv_usec = xdr.xdrDecodeInt();
    }

}
// End of rstat_timeval.java
